# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:alpine AS builder

# Install git for fetching dependencies
RUN apk add --no-cache git

WORKDIR /app

# Copy go mod files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the MCP server binary
RUN CGO_ENABLED=0 go build -o mcp_demo main.go

FROM alpine:latest
WORKDIR /app

# Copy the built binary from the builder stage
COPY --from=builder /app/mcp_demo ./

# Expose the SSE port (if needed)
EXPOSE 8000

# Start the server with a default token. The token value should be overridden via Smithery config.
CMD ["./mcp_demo", "--token", "secret-token", "--transport", "stdio"]
